import "./globals.css";
import type { Metadata } from "next";
import { Fjalla_One } from "next/font/google";

const fjalla_One = Fjalla_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={fjalla_One.className} style={{ margin: 0 }}>
        {children}
      </body>
    </html>
  );
}
