import "./globals.css";
import type { Metadata } from "next";
import { Fjalla_One, Molengo } from "next/font/google";

const fjallaOne = Fjalla_One({ weight: "400", variable: "--font-fjalla-one", subsets: ["latin"] });
const molengo = Molengo({ weight: "400", variable: "--font-molengo", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${fjallaOne.variable} ${molengo.variable}`}>
      <body className={`${fjallaOne.className}`} style={{ margin: 0 }}>
        {children}
      </body>
    </html>
  );
}
